@HOST = localhost
@PORT = 1234

GET http://{{HOST}}:{{PORT}}/

# --- Rutas API --- 

### Obtener infomación de todos los poemas
GET http://{{HOST}}:{{PORT}}/poems

### Obtener infomación un poema por id
GET http://{{HOST}}:{{PORT}}/poems/f4758805-73a5-4353-b56e-a5b7c9aad201

### Obtener infomación de poemas filtrados por writer
GET http://{{HOST}}:{{PORT}}/poems?writer=Antonio%20Machado

### Crear un poema
POST http://{{HOST}}:{{PORT}}/poems
Content-Type: application/json

{
    "poem": "caminante no hay camino",
    "writer": "Antonio Machado",
    "year_publication": 1912
}

### Actualizar un poema
PATCH http://{{HOST}}:{{PORT}}/poems/b842b093-7fe5-4a25-84c7-1a74f65643d9
Content-Type: application/json

{
    "year_publication": 1812
}

### Eliminar un poema
DELETE http://{{HOST}}:{{PORT}}/poems/8b0fd9b0-4f2e-4e6c-890b-f947c70675ec