@HOST = localhost
@PORT = 1234

GET http://{{HOST}}:{{PORT}}/

# --- Rutas API --- 

### Obtener infomación de todos los poemas
GET http://{{HOST}}:{{PORT}}/poems

### Obtener infomación un poema por id
GET http://{{HOST}}:{{PORT}}/poems/6ec51d58-aa65-450f-99f0-0deba105b6cc

### Obtener infomación de poemas filtrados por writer
GET http://{{HOST}}:{{PORT}}/poems?writer=Antonio%20Machado

### Crear un poema
POST http://{{HOST}}:{{PORT}}/poems
Content-Type: application/json

{
    "poem": "caminante no hay camino",
    "writer": "Antonio Machado",
    "year_publication": 1912
}

### Actualizar un poema
PATCH http://{{HOST}}:{{PORT}}/poems/e066887d-a5ca-4e42-a7f4-25f0c6dadda4
Content-Type: application/json

{
    "year_publication": 1812
}

### Eliminar un poema
DELETE http://{{HOST}}:{{PORT}}/poems/e066887d-a5ca-4e42-a7f4-25f0c6dadda4